services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "composer install --no-interaction --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:8000 -t public"
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: your_secret_here
      - key: DATABASE_URL
        value: mysql://user:password@hostname:port/dbname
