<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ji3FXXiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ji3FXXi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ji3FXXi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeRepo' => ['privates', 'App\\Repository\\EmployeeRepository', 'getEmployeeRepositoryService', true],
        ], [
            'employeeRepo' => 'App\\Repository\\EmployeeRepository',
        ]);
    }
}
