<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3cFpdBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H3cFpdB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H3cFpdB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entretien' => ['privates', '.errored..service_locator.H3cFpdB.App\\Entity\\Entretien', NULL, 'Cannot autowire service ".service_locator.H3cFpdB": it needs an instance of "App\\Entity\\Entretien" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entretien' => 'App\\Entity\\Entretien',
        ]);
    }
}
