<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTYxsStService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WTYxsSt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WTYxsSt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'builderInterface' => ['privates', 'Endroid\\QrCode\\Builder\\Builder', 'getBuilderService', true],
            'presenceRepository' => ['privates', 'App\\Repository\\PresenceRepository', 'getPresenceRepositoryService', true],
        ], [
            'builderInterface' => '?',
            'presenceRepository' => 'App\\Repository\\PresenceRepository',
        ]);
    }
}
