<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KCWWtffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kCWWtff' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kCWWtff'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'budget' => ['privates', '.errored..service_locator.kCWWtff.App\\Entity\\Budget', NULL, 'Cannot autowire service ".service_locator.kCWWtff": it needs an instance of "App\\Entity\\Budget" but this type has been excluded in "config/services.yaml".'],
        ], [
            'budget' => 'App\\Entity\\Budget',
        ]);
    }
}
