<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MmMs999Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mmMs999' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mmMs999'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assuranceRepository' => ['privates', 'App\\Repository\\AssuranceRepository', 'getAssuranceRepositoryService', true],
        ], [
            'assuranceRepository' => 'App\\Repository\\AssuranceRepository',
        ]);
    }
}
