<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YWbbzUUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yWbbzUU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yWbbzUU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'entretien' => ['privates', '.errored..service_locator.yWbbzUU.App\\Entity\\Entretien', NULL, 'Cannot autowire service ".service_locator.yWbbzUU": it needs an instance of "App\\Entity\\Entretien" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'entretien' => 'App\\Entity\\Entretien',
        ]);
    }
}
