<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HGexNbGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hGexNbG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hGexNbG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offreemploi' => ['privates', '.errored..service_locator.hGexNbG.App\\Entity\\Offreemploi', NULL, 'Cannot autowire service ".service_locator.hGexNbG": it needs an instance of "App\\Entity\\Offreemploi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'offreemploi' => 'App\\Entity\\Offreemploi',
        ]);
    }
}
