<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HjGplcyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hjGplcy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hjGplcy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conge' => ['privates', '.errored..service_locator.hjGplcy.App\\Entity\\Conge', NULL, 'Cannot autowire service ".service_locator.hjGplcy": it needs an instance of "App\\Entity\\Conge" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conge' => 'App\\Entity\\Conge',
        ]);
    }
}
