<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RfmnC1ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RfmnC1Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RfmnC1Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'rh' => ['privates', '.errored..service_locator.RfmnC1Z.App\\Entity\\Rh', NULL, 'Cannot autowire service ".service_locator.RfmnC1Z": it needs an instance of "App\\Entity\\Rh" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'rh' => 'App\\Entity\\Rh',
        ]);
    }
}
