<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConge2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hjGplcy.App\Entity\Conge' shared service.
     *
     * @return \App\Entity\Conge
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hjGplcy": it needs an instance of "App\\Entity\\Conge" but this type has been excluded in "config/services.yaml".');
    }
}
