<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOCRServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OCRService' shared autowired service.
     *
     * @return \App\Service\OCRService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OCRService.php';

        return $container->privates['App\\Service\\OCRService'] = new \App\Service\OCRService();
    }
}
