<?php

namespace ContainerXoXtqQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPresenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8oEUbtU.App\Entity\Presence' shared service.
     *
     * @return \App\Entity\Presence
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8oEUbtU": it needs an instance of "App\\Entity\\Presence" but this type has been excluded in "config/services.yaml".');
    }
}
