controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_recherche_assurance:
    path: /recherche-assurance
    controller: App\Controller\RechercheAssuranceController::search
    methods: [GET, POST]

    