<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoXtqQV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoXtqQV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXoXtqQV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXoXtqQV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXoXtqQV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XoXtqQV',
    'container.build_id' => '2c90adc6',
    'container.build_time' => 1746487427,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoXtqQV');
